### ISSUE TITLE
Decorators in jest?

### ISSUE THREAD

**Issue by DarrylD** [kitze/custom-react-scripts#100]
Like most, I started using this variant of CRA for the decorators. Backfires when trying to use Jest. Is it a way to use Jest with decorators?

**Comment by jason-henriksen** [comment]
I thought you fixed this recently, but now I am seeing the same issue on 0.2.0.

**Comment by jason-henriksen** [comment]
OK, I see the problem.  The fix that was provided on issue 94:
https://github.com/kitze/custom-react-scripts/pull/94

Is for some reason not in the builds.  Maybe the builds are running from a branch or something?
This is why my work computer is OK, but my other computers are not.  I manually patched in the fix on my work computer.

If you want to locally patch your system to get up and running you can take the file from here:
https://github.com/dforsten/custom-react-scripts/blob/c402e1a2518dd039645ecedd8d5ed5c2093a845f/packages/react-scripts/config/jest/babelTransform.js

Copy that file into your local set of files and things will work fine.  Ideally, you could just wait for him to fix it, but if you need to get up and running today this file will get you going.

**Comment by DarrylD** [comment]
thanks @jason-henriksen, i'll give this a try

**Comment by ecstasy2** [comment]
+1 on fixing this.

**Comment by fmsouza** [comment]
I've already tried @jason-henriksen fix and it actually works very well. The problem for me is that I need it to be working on clean builds as well, as my application goes through a CI process before building. So this kind of manual fixes won't work, unless I add my whole `node_modules` to versioning...

**Comment by DarrylD** [comment]
I'm kinda in the same boat...

**Comment by jseminck** [comment]
Same problem for me. A release would be great!

**Comment by fmsouza** [comment]
@kitze Do you have an ETA for a new build with this fix?

**Comment by gvasilei** [comment]
This fix would make my life so much easier! Please add to a release when possible :)

**Comment by wichopy** [comment]
@fmsouza As a workaround to customizing a clean build for CI with decorators, I've checked in the modified react script config files in my repo and copied over the files to my node_modules folder as part of the install phase of my CI pipeline.

Something like this in Jenkins:
```
stage('Build Client') {
        sh "${nodeHome}/bin/node -v"
        dir("${env.WORKSPACE}") {
            sh "npm install"
            sh "cp ./customNodeModuleFiles/webpack.config.dev.js ./node_modules/react-scripts/config/webpack.config.dev.js"
            sh "cp ./customNodeModuleFiles/webpack.config.prod.js ./node_modules/react-scripts/config/webpack.config.prod.js"
            sh "npm run build"
        }
    }


```

Not the prettiest solution but it got the job done for me until we get decorators included with CRA.
