### ISSUE TITLE
CPU, RAM drain

### ISSUE THREAD

**Issue by Otas13** [kitze/custom-react-scripts#110]
Hello, im experiencing big resources drain on windows. With normal react-scripts there were only one process that consumed ~450MB of RAM, but with custom react scripts there is about 3 more processes that were keeping about 40MB, but now are at 300 - 400MB. I've checked if node_modules folder is under ignored in webpack config, and it is. Anyone else experiencing this trouble? I really need sass modules in my project, so i need to solve this. Every help would be great.
![wtf](https://user-images.githubusercontent.com/10956918/31301313-5c1ff11e-aaf9-11e7-97d8-72e06f371b7c.png)
CPU is at 90% at some point, which in combination with 90% of RAM really bad

**Comment by marcosfede** [comment]
Also experiencing this issue, It spawns 4 node processes and keeps my cpu at almost 100%

**Comment by kitze** [comment]
@Otas13 any idea what can cause it?
