### ISSUE TITLE
How I add stylus options?

### ISSUE THREAD

**Issue by exdeniz** [kitze/custom-react-scripts#117]
Like
```
{
          loader: 'stylus-loader',
          options: {
            use: [rupture()],
          }
        }
```

**Comment by ericmmartin** [comment]
As far as I can tell, you can only enable/disable the loader...unless you want to submit a PR or fork the repo.

**Comment by kitze** [comment]
@ericmmartin is right. If you want those options you will have to submit a PR @exdeniz. I don't use stylus in my projects so I don't need them.
