### ISSUE TITLE
can't use react-app-rewired

### ISSUE THREAD

**Issue by DayDarkDark** [kitze/custom-react-scripts#122]
when I use react-app-rewired, like this :
https://mobile.ant.design/docs/react/use-with-create-react-app-cn
has error :
$ react-app-rewired start
module.js:538
    throw err;
    ^

Error: Cannot find module 'react-scripts/package.json'

**Comment by RIP21** [comment]
Because it's not create-react-app. It's custom-react-scripts. Please watch https://github.com/facebookincubator/create-react-app
And use them.

**Comment by kitze** [comment]
@DayDarkDark If you want to use react-app-rewired you need to use the original create-react-app and react-scripts.
