### ISSUE TITLE
how to use this package in an existing create-react-app ?

### ISSUE THREAD

**Issue by zetekla** [kitze/custom-react-scripts#127]
how to use this package in an existing create-react-app ? Can I just install it with `npm i -S custom-react-scripts-ts` and replace `react-scripts start` with `custom-react-scripts start` in package.json?

**Comment by clintandrewhall** [comment]
I’m not at my laptop, but this was something I neede, too.  I can post/pull request instructions when I get home... but I was able to by creating a dummy app and comparing my package.json file.

Be sure to blow away any custom .babelrc and your node_modules.  I use Flow and my babelrc file ruined everything.

I’ll make a note to add a pull request with my end result.

**Comment by rafiuske** [comment]
This is simple. In my project, I inserted the ``` "custom-react-scripts": "0.0.23" ``` on **package.json**  and run the ``` npm install ```  command. After this, you will need to create the environment file **.env** in the root and modify the [configuration options](https://github.com/kitze/custom-react-scripts#-configuration-options).

**Comment by ivanberry** [comment]
@rafiuske is need to replace the **react-scripts start** to **custom-react-scripts start** in **package.json**

**Comment by zetekla** [comment]
@rafiuske I will give it a try and report back! Thank you for your input.

**Comment by kitze** [comment]
https://github.com/kitze/custom-react-scripts#adding-to-an-existing-project
