### ISSUE TITLE
Is this for still active?

### ISSUE THREAD

**Issue by tonyneel923** [kitze/custom-react-scripts#128]
I would like to know if this fork is kept up to date with create-react-app. Thanks.

**Comment by ericmmartin** [comment]
Current react-scripts version is 1.1.0 and the README says it is using 1.0.11. So no, it has not been kept up to date with recent updates.

**Comment by artemirq** [comment]
@tonyneel923 If you actually now need latest `react-scripts` with features, check  https://github.com/artemirq/advanced-react-scripts

**Comment by ortonomy** [comment]
@kitze -- any plans to update the react-scripts in this package to 1.1?

**Comment by k1sul1** [comment]
artemirq/advanced-react-scripts is more up to date, but those of us that use Stylus are out of luck. SCSS is just too verbose for me.

Might as well move away from CRA when this fork will not do anymore, relying on other peoples forks isn't a good long term solution anyway. Those that hate configuring Webpack might find Parcel useful.

**Comment by artemirq** [comment]
@k1sul1 If you need feature in [advanced-react-scripts](https://github.com/artemirq/advanced-react-scripts), you must create issue :)

**Comment by artemirq** [comment]
@k1sul1 I added support Stylus in [advanced-react-scripts](https://github.com/artemirq/advanced-react-scripts), but not tested. Would be good if someone tested this :)

**Comment by k1sul1** [comment]
I'll see if I've time for my side project during the weekend @artemirq 

Thanks for the effort! I configured Webpack from scratch today for a work project so if it doesn't I might find out what's wrong.

**Comment by artemirq** [comment]
@k1sul1 Thank you :)

**Comment by kitze** [comment]
If someone sends a PR for updating to the latest react-scripts version, I would gladly accept it and release a new version.

**Comment by k1sul1** [comment]
@artemirq I was too busy last weekend, but I managed to test advanced-react-scripts. The good news is that the stylus-loader is working like it should, but  it didn't like my code. I guess I'm relying on some stage-2 or stage-1 proposal, I got this error : 

```
./src/components/Workbench.js
Module build failed: Thread Loader (Worker 0)
We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
``` 

There's something in this that it doesn't like

```javascript
const boxTarget = {
  drop(props, monitor, component) {
    const item = monitor.getItem()
    console.log(component, item.unique, component[item.unique]);
    window.component = component;

    return {
      key: 'workbench',
    }
  },
}

@DropTarget(ItemTypes.FIELD, boxTarget, (connect, monitor) => ({
  connectDropTarget: connect.dropTarget(),
  isOver: monitor.isOver(),
  canDrop: monitor.canDrop(),
}))
export default class Workbench extends Component {
  static propTypes = {
    tree: PropTypes.array.isRequired,
    connectDropTarget: PropTypes.func.isRequired,
    isOver: PropTypes.bool.isRequired,
    canDrop: PropTypes.bool.isRequired,
  }

  static defaultProps = {
    tree: [],
  }

  render() {
    const { tree } = this.props;
    const { canDrop, isOver, connectDropTarget } = this.props
    const isActive = canDrop && isOver

    if (tree.length) {
      console.log(tree);
    }

    let backgroundColor = null
    if (isActive) {
      backgroundColor = 'darkgreen'
    } else if (canDrop) {
      backgroundColor = 'darkkhaki'
    }

    return connectDropTarget(
      <div style={{backgroundColor}} className={this.props.className}>
        {tree.map((field, index) => {
          const { key, attributes, parent, unique } = field;
          if (parent === 'workbench') {
            return (
              <Field
                TagName={`input`}
                title={key}
                attributes={attributes}
                remove={() => false}
                unique={unique}
                key={key}
                _key={key}
                parent={this}
              />
            );
          }

          return null;
        }).filter(Boolean)}
      </div>,
    )
  }
}
```

I'm in the middle of implementing react-dnd, don't look for sense in the code.  I  enabled decorators and class properties in the .env file.

And for the 5 others subbed to this issue; sorry.  This discussion should probably continue elsewhere.

**Comment by artemirq** [comment]
@k1sul1 Yeah, [it's bug](https://github.com/babel/babel/issues/7177) in babel >= 7.0.0-beta.37. I tried fix this bug in `test` version of advanced-react-scripts(`0.3.47-beta.12`). Try this version, please

**Comment by kitze** [comment]
@artemirq and @k1sul1 can you please discuss other packages in their respective repo? Thanks.

**Comment by Eric-Arellano** [comment]
@kitze hello, when possible could you please publish the changes since March? I'm not sure how to integrate the upgrade to FB's scripts I made last month.

I'm happy to help publish, only not sure how to do so and think you might need to. Let me know how to be helpful!

**Comment by Eric-Arellano** [comment]
Hey all, see this commit from @kitze for some alternatives now that Create React App 2 is released https://github.com/kitze/custom-react-scripts/commit/841a8e2b53ef956d027d30e7843383fb86c60fb0. Thanks again Kitze!

**Comment by kitze** [comment]
Please use this one from now on:
https://github.com/arackaf/customize-cra
