### ISSUE TITLE
Responding to question on code

### ISSUE THREAD

**Issue by enjoythelive1** [kitze/custom-react-scripts#133]
https://github.com/kitze/custom-react-scripts/blob/dea4a2ba0c422333e75114c63158ae2af8cbce3c/packages/react-scripts/scripts/utils/createJestConfig.js#L23

It is, NodeJS path is understands '/' as path separator.

**Comment by kitze** [comment]
What is the issue here @enjoythelive1 ? This code is part of the original react-scripts.
