### ISSUE TITLE
react-toolbox - default styles are applied

### ISSUE THREAD

**Issue by tvojtech** [kitze/custom-react-scripts#42]
Trying to use react-toolbox in React app created by `create-react-app` with `custom-react-scripts` but no styles are applied. [Here](https://github.com/tvojtech/react-toolbox-theme-not-applied) is an app that does not work. 

Result looks like 
![image](https://cloud.githubusercontent.com/assets/1427446/21290038/dcf973d4-c4ac-11e6-8564-311b84d3841c.png)

Changing `custom-react-scripts/config/customizers.js` [this way](https://github.com/tvojtech/react-toolbox-theme-not-applied/blob/master/src/customizers.js#L23) fixes the problem but I don't expect this to be proper solution. I'm new to webpack and stuff around it.

From
````
loader: "style!css!postcss!sass"
````

to (see [example for react-toolbox](https://github.com/react-toolbox/react-toolbox-example/blob/master/webpack.config.js))
````
loader: "style!css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass"
````
 
![image](https://cloud.githubusercontent.com/assets/1427446/21290053/33793fdc-c4ad-11e6-855f-8556c53a0c78.png)

Is this problem of the customizer or am I doing something wrong?

**Comment by cyxn** [comment]
I also have exact same problem. With react-toolbox and groomet - both required css modules

**Comment by kitze** [comment]
Hey @cyxn and @tvojtech , the dev of react-toolbox suggests that you should try this method of using it instead -> https://github.com/react-toolbox/react-toolbox-themr 

You don't need to customize create-react-app.

Try it and let me know.
