### ISSUE TITLE
Implement support for react-intl

### ISSUE THREAD

**Issue by treyspiva** [kitze/custom-react-scripts#54]
Is there any plans to implement support react-intl.  Adding React-Intl is not a really big deal. You can easily do an npm install to add react-intl.  The problem is to build message files I am using babel-plugin-react-intl.  The babel plugin needs to update the .babelrc file.  I am not able to get to the .babelrc file without ejecting.  So, I am hoping for a better solution.

Thanks.

**Comment by kitze** [comment]
Hey @treyspiva, unfortunately to do any type of babel/webpack custom modifications you must eject. This project won't support them. 

Cheers!
