### ISSUE TITLE
Use package json instead of .env

### ISSUE THREAD

**Issue by viankakrisna** [kitze/custom-react-scripts#65]
.env is not checked to git, i think it's better to set the customization in the package.json. It would make the projects generated by this easier to share. thoughts?

**Comment by kitze** [comment]
@viankakrisna I changed my mind about this because the CRA team is using .env for configuring the project, so the options will remain in .env.

**Comment by lnhrdt** [comment]
This doesn't provide an obvious solution for putting custom-react-scripts configuration under source control though – .env is commonly excluded from source control because it often contains sensitive information / secrets. Thoughts?

**Comment by viankakrisna** [comment]
I'm on a phone now, so i cant link much. but the convention from cra is .env is checked to git. So i think it's safe to close this. You can see the generated .gitignore to see which .env is ignored.

**Comment by viankakrisna** [comment]
you can use https://github.com/facebookincubator/create-react-app/blob/80a7fc391df112bcb9f2c669b3932d4b3d0856fc/packages/react-scripts/template/gitignore#L14-L17 to store environment specific variables. 

here's the docs for it https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-development-environment-variables-in-env
