### ISSUE TITLE
question about decorators

### ISSUE THREAD

**Issue by smmoosavi** [kitze/custom-react-scripts#67]
I read your code and I can't find how decorator added to babel

I find this [code](https://github.com/kitze/custom-react-scripts/blob/master/packages/react-scripts/config/customizers.js#L10-L15) in `customizers.js` file and [how](https://github.com/kitze/custom-react-scripts/blob/master/packages/react-scripts/config/get-custom-config.js#L16-L19) `getCustomConfig` function use `toArray` value. But I can't find where [`babelPlugins` variable](https://github.com/kitze/custom-react-scripts/blob/master/packages/react-scripts/config/get-custom-config.js#L28) used.

can you help me I find where `babelPlugins` value added to babel config?

**Comment by kitze** [comment]
The point of this fork is to add decorators by just adding: ```REACT_APP_DECORATORS=true``` to an .env file in your project root. You don't have to mess with babel.
