### ISSUE TITLE
Remove experimental decorators warning in vs code

### ISSUE THREAD

**Issue by jwamsterdam** [kitze/custom-react-scripts#70]
I have enabled experimental decorators in the .env file, but how do I remove the red warnings underlining my code in vs code?

**Comment by kitze** [comment]
http://stackoverflow.com/questions/38271273/experimental-decorators-warning-in-visual-studio-code

**Comment by jwamsterdam** [comment]
The link provided by Kitze did not work for me. This one did work: 
https://ihatetomatoes.net/how-to-remove-experimentaldecorators-warning-in-vscode/
