### ISSUE TITLE
Updating to latest CRA

### ISSUE THREAD

**Issue by timworx** [kitze/custom-react-scripts#78]
Any word on updating to the latest CRA? I saw a few months ago in a closed issue that you mentioned working towards it.

Cursory diff checks didn't show too terrible of a task ahead, let me know if you'd like any help!

**Comment by alexrussell** [comment]
Also, the readme should probably mention (and be kept up-to-date with) what version of CRA this package *is* currently 'mirroring' so people can make an informed decision about the use of the package.

**Comment by alexrussell** [comment]
Just realised it does say this quite obviously at the top of the readme, so please ignore my last comment.

**Comment by themre** [comment]
any plan to update to CRA 1.0? RC is out.

**Comment by bensleveritt** [comment]
And now the full release!

**Comment by chemitaxis** [comment]
Hi, any news about it? Thanks!

**Comment by thezanke** [comment]
@kitze mentions plans to update along with the new CRA changes in this thread https://github.com/kitze/custom-react-scripts/issues/71#issuecomment-286872173 that said, not sure if he's abandoned this or not.

**Comment by timworx** [comment]
@thezanke Sorry - should have referenced that specifically above. But that is indeed what I was referring to by "I saw a few months ago in a closed issue that you mentioned working towards it."

As an update, CRA v1.x is quite well featured. I was primarily using this for SASS support. I switched two of my projects back over to CRA, used their SASS instruction, and it didn't take much time at all.

You're still out of luck if you need Babel stage 0 or decorator support, though.

**Comment by thezanke** [comment]
Decorators is why I'm here 😭

**Comment by nickretallack** [comment]
With no updates in 6 months, it seems this package is abandoned.  I need the newer version of react-scripts for its new proxy settings.  Guess I'll have to eject.

**Comment by kitze** [comment]
Updated to latest version (with webpack 3) + added support for css/sass/less/stylus modules 🎉

**Comment by alexrussell** [comment]
Well that escalated quickly!
