### ISSUE TITLE
Add to existing app

### ISSUE THREAD

**Issue by dschinkel** [kitze/custom-react-scripts#80]
is there a way to apply this to an existing create-react-app?   I'd like to be able to add an .env file so I could start using it in an existing app...

**Comment by saalihou** [comment]
Yes apparently:
https://github.com/kitze/custom-react-scripts/issues/30

**Comment by dschinkel** [comment]
thanks.  I ultimately went this route: https://www.codementor.io/daveschinkel13/running-mocha-enzyme-with-creat-react-app-84flnngkk

**Comment by dschinkel** [comment]
I'll update my blog post to put a good mention in for custom-react-scripts as well

**Comment by kitze** [comment]
Thanks @dschinkel 👌
