### ISSUE TITLE
Custom react scripts on a build server ?

### ISSUE THREAD

**Issue by madwill** [kitze/custom-react-scripts#83]
> How to use

Present the idea of scaffolding create-react-app with custom-react-script which is nice

But what if one needs to builds from existing source or more importantly in this case, build on a server ?

If i do a normal npm install and then npm run build i get the expected "unexpected token" error. How can i make custom-react-script be run everywhere instead of just where i scaffolded my app

Thank you very much ! 

```
Module build failed: SyntaxError: Unexpected token (7:2)


   5 | class test{
   6 |   somevar = ''
>  7 |   @observable someothervar;
     |   ^
   8 | 
   9 |   constructor(){
  10 |     this.someothervar = 'this'



```

**Comment by BenBenz** [comment]
I have the same error @madwill, I'm looking to a solution

**Comment by madwill** [comment]
I ejected. Good luck Ben!

**Comment by kitze** [comment]
@BenBenz @madwill don't forget to commit .env file to git. That was the problem.
