### ISSUE TITLE
Feature Request: add .env*.local support

### ISSUE THREAD

**Issue by achntrl** [kitze/custom-react-scripts#88]
create-react-app incorporated a feature that allow using local env files. It would be nice to have this on custom react scripts too to avoid the versioning of local url and/or production passwords

The file responsible for that can be found there
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/env.js

Thanks !

**Comment by skeet** [comment]
I just tested this and it already seems to work.

My `.env.production.local` file takes precedence over `.env` when I run `yarn build`.

Just remember to make sure that damn serviceworker isn't caching things...
