### ISSUE TITLE
Decorators work... but not with npm run test

### ISSUE THREAD

**Issue by jason-henriksen** [kitze/custom-react-scripts#92]
### Is this a bug report?

Yes

### Can you also reproduce the problem with npm 4.x?

NPM 5.3.0 fails.
Yarn 0.27.5 fails.
I did not try going back to npm v4.

### Which terms did you search for in User Guide?

I searched for test and decorators.  MobX, etc.  No luck.

### Environment
NPM 5.3.0
node v6.9.2
custom-react-scripts: 0.1.4
react-scripts does not come up.

Windows 10 + Chrome

### Steps to Reproduce

I'm using MobX with decorators.  They work fine when I use **npm start**.
However, when I try to use the test runner it tells me that it doesn't know what the @ operator means.
1.  Use MobX with decorators
2.  See that the website works correctly
3.  See that the tests fail 

### Expected Behavior

Tests run and jsx is compiled the same way that it is for a run in the node.js server.

### Actual Behavior

Test fails because it appears unable to handle the decorator.

FAIL  src\UI\Pages\Login\LoginPage.test.js
  ● Test suite failed to run
    C:/src2/Development/Products/Suite/Main/Server.TC2.UI/src/UI/Pages/Login/LoginPage.jsx: Unexpected token (12:0)
        10 |
        11 |
    > 12 | @inject("CoreData") @observer
            | ^
       13 | class LoginPage extends Component {

I tried altering the package.json from this:
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }

to this:
  "scripts": {
    "start": "custom-react-scripts start",
    "build": "custom-react-scripts build",
    "test": "custom-react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }

but it did not help.

Thank you for any ideas or suggestions!

**Comment by kitze** [comment]
Oooh I have to fix this, tnx @jason-henriksen

**Comment by kitze** [comment]
Fixed.

**Comment by jason-henriksen** [comment]
I'm sorry to be dense, I'm relatively new to this ecosystem.

I used git to clone the repository, then "yarn --check-files" to load dependencies, the "yarn build" to try to build something.  But the output doesn't look anything like what I have in my node_modules.  I also can't find a way to get these changes into my system via npm.

I'm sorry to ask for remedial education, but I'm not sure how to apply the change you made to see if it fixes the problem for me.
